version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongo-data:/data/db
    ports:
      - '27017:27017'
    networks:
      - app-network

  backend:
    build: ./BACKEND
    container_name: backend-dev
    command: npm run dev
    volumes:
      - ./BACKEND:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '5000:5000'
    depends_on:
      - mongodb
    networks:
      - app-network
    environment:
      - NODE_ENV=development
      - CLIENT_ORIGIN=http://localhost:3000
      - MONGO_URI=mongodb://mongodb:27017/ecole-ukrainienne

  frontend:
    build: ./FRONTEND
    container_name: frontend-dev
    command: npm start
    volumes:
      - ./FRONTEND/src:/app/src
      - ./FRONTEND/public:/app/public
    ports:
      - '3000:3000'
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:5000/api
      - REACT_APP_GOOGLE_CLIENT_ID=${REACT_APP_GOOGLE_CLIENT_ID}

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
